---
sudo: false
language: ruby
rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0
  - ruby-head
  - jruby-9.0
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
gemfile:
  - Gemfile
before_script:
  - |
    case "${TRAVIS_RUBY_VERSION}" in
      rbx*)
        gem install psych
        ;;
    esac
  - rake travis:before -t
script: rake travis
after_script:
  - rake travis:after -t
notifications:
  email:
    recipients:
      - halostatue@gmail.com
    on_success: change
    on_failure: always
